-- 在 Supabase Dashboard → SQL Editor 中完整执行一次。
-- 应用从 Streamlit 服务器使用 service_role 密钥访问，因此保留 RLS，
-- 但不创建面向浏览器客户端的公开策略。

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password_hash text not null,
  role text not null check (role in ('admin', 'student')),
  student_no text unique,
  display_name text not null,
  created_at timestamp without time zone not null
);

create table if not exists public.assignments (
  id bigint generated by default as identity primary key,
  subject text not null,
  title text not null,
  requirements text not null,
  deadline timestamp without time zone not null,
  created_at timestamp without time zone not null
);

create table if not exists public.submissions (
  id bigint generated by default as identity primary key,
  assignment_id bigint not null references public.assignments(id) on delete cascade,
  student_id bigint not null references public.users(id) on delete cascade,
  filename text not null,
  saved_path text not null,
  submitted_at timestamp without time zone not null,
  is_late boolean not null,
  unique (assignment_id, student_id)
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  created_at timestamp without time zone not null
);

create index if not exists submissions_assignment_id_idx on public.submissions (assignment_id);
create index if not exists submissions_student_id_idx on public.submissions (student_id);

-- 私有附件桶：最大单个文件 50 MB。service_role 从 Streamlit 服务器访问，
-- 学生浏览器不会拿到该密钥或公开下载链接。
insert into storage.buckets (id, name, public, file_size_limit)
values ('homework-files', 'homework-files', false, 52428800)
on conflict (id) do nothing;

alter table public.users enable row level security;
alter table public.assignments enable row level security;
alter table public.submissions enable row level security;
alter table public.notifications enable row level security;
